### ISSUE TITLE
Arm joint configuration (motor positions)

### ISSUE THREAD

**Issue by anht-nguyen** [Rehab-Robotics-Lab/FloSystemV2#68]
(Update 3/12/2024) Left arm motors: neutral position, range of motion
111: neutral 5600, 3500 - 6700
112: neutral 4083, 2000 - 4200
121: neutral 1000, 960 - 2000
122: neutral 4100, 4900 - 3300

**Comment by ajyanand** [comment]
added further joint limits after testing
